# Generated by Django 5.1.4 on 2026-03-30 05:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_scope', models.CharField(choices=[('user', 'User'), ('org', 'Organization')], max_length=10)),
                ('owner_user_id', models.UUIDField(blank=True, null=True)),
                ('owner_org_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('created_by_user_id', models.UUIDField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='files.folder')),
            ],
        ),
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_scope', models.CharField(choices=[('user', 'User'), ('org', 'Organization')], max_length=10)),
                ('owner_user_id', models.UUIDField(blank=True, null=True)),
                ('owner_org_id', models.UUIDField(blank=True, null=True)),
                ('created_by_user_id', models.UUIDField()),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('org', 'Organization'), ('public', 'Public'), ('shared', 'Shared')], default='private', max_length=10)),
                ('status', models.CharField(choices=[('upload_pending', 'Upload Pending'), ('uploading', 'Uploading'), ('active', 'Active'), ('failed', 'Failed'), ('aborted', 'Aborted'), ('deleted', 'Deleted')], default='upload_pending', max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('extension', models.CharField(blank=True, default='', max_length=32)),
                ('mime_type', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('storage_bucket', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=1024, unique=True)),
                ('storage_version_id', models.CharField(blank=True, max_length=255, null=True)),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('stable_url', models.URLField(max_length=512, unique=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.folder')),
            ],
        ),
        migrations.CreateModel(
            name='MultipartUpload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_upload_id', models.CharField(max_length=255)),
                ('part_size_bytes', models.BigIntegerField()),
                ('parts_expected', models.IntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('aborted', 'Aborted'), ('expired', 'Expired'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multipart_upload', to='files.fileasset')),
            ],
        ),
        migrations.CreateModel(
            name='MultipartUploadPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_number', models.IntegerField()),
                ('etag', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('multipart_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='files.multipartupload')),
            ],
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner_scope', 'owner_user_id'], name='files_folde_owner_s_743a82_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner_scope', 'owner_org_id'], name='files_folde_owner_s_034418_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent'], name='files_folde_parent__2ff01a_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['owner_scope', 'owner_user_id', 'status'], name='files_filea_owner_s_786212_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['owner_scope', 'owner_org_id', 'status'], name='files_filea_owner_s_7a15ee_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['folder', 'status'], name='files_filea_folder__795d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['visibility', 'status'], name='files_filea_visibil_794e03_idx'),
        ),
        migrations.AddIndex(
            model_name='multipartupload',
            index=models.Index(fields=['status', 'expires_at'], name='files_multi_status_09d0ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='multipartuploadpart',
            unique_together={('multipart_upload', 'part_number')},
        ),
    ]
